[package]
name = "hello"
version = "0.1.0"
edition = "2021"
<<<<<<< HEAD
description = "This library only displays \"ðŸ¹Hello WorldðŸ¹\""
=======
description = "This library only displays "ðŸ¹Hello WorldðŸ¹""
>>>>>>> 61383ce7d8f06af84854f8aa086dc6d2449c49cb
license = "MIT OR Apache-2.0"
repository = "https://github.com/cuticle999/hello-world-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]