[package]
name = "hello"
version = "0.1.0"
edition = "2021"
description = "This library only displays \"ğŸ¹Hello WorldğŸ¹\""
license = "MIT OR Apache-2.0"
repository = "https://github.com/cuticle999/hello-world-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]